#!/usr/bin/env python3
"""
Build a tailored resume for a specific company/application.

Each company lives in its own subfolder under applications/ and provides
tailored override sections (objective / skills / projects) plus an
ATS-clean markdown file. The BASE resume in the resume repo's resume/sections/ is the source of
truth; a company folder only overrides what it needs to.

Two outputs per company:
  1. sunil_resume_<company>.pdf       -> polished LaTeX, for humans / LinkedIn / Wellfound
  2. sunil_resume_<company>_ATS.docx  -> plain single-column, for Workday / Greenhouse ATS

Usage:
    python build.py capital-one
    python build.py capital-one --pdf-only
    python build.py capital-one --ats-only
"""
import argparse
import os
import shutil
import subprocess
import sys

# The base resume (sections/, TLCresume.sty, sourcesanspro.sty) lives in the
# resume repo, a separate tree; applications/ lives with the tool. paths.py is
# the one place that knows either.
from jobpilot.core.paths import RESUME as RESUME_DIR, APPLICATIONS as APPLICATIONS_DIR, TOOL as TOOL_ROOT  # noqa: E402


def build_pdf(company_dir, company):
    resume_tex = os.path.join(company_dir, "resume.tex")
    if not os.path.isfile(resume_tex):
        print(f"  [pdf] SKIP: no resume.tex in {company_dir}")
        return None
    # resume.tex imports ./sections/ (the application's own copy). TEXINPUTS
    # supplies TLCresume.sty / sourcesanspro.sty from the resume repo.
    env = dict(os.environ)
    env["TEXINPUTS"] = f".:{RESUME_DIR}:{TOOL_ROOT}:" + env.get("TEXINPUTS", "")
    for _ in range(2):                      # two passes so \hfill / refs settle
        proc = subprocess.run(
            ["pdflatex", "-interaction=nonstopmode", "-halt-on-error", "resume.tex"],
            cwd=company_dir, env=env, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    if proc.returncode != 0:
        print(proc.stdout.decode(errors="replace")[-2000:])
        print(f"  [pdf] FAILED for {company}")
        return None
    out = os.path.join(company_dir, "sunil_resume.pdf")
    shutil.move(os.path.join(company_dir, "resume.pdf"), out)
    for ext in (".aux", ".log", ".out"):
        f = os.path.join(company_dir, "resume" + ext)
        if os.path.isfile(f):
            os.remove(f)
    print(f"  [pdf] {out}")
    return out


def build_ats(company_dir, company):
    """ats.md is DERIVED from sections/*.tex here, then pandoc makes the .docx.
    Nobody edits ats.md: the .docx an ATS parses is always the same content as
    the PDF a human reads."""
    from jobpilot.tailor import tex2md
    ats_md = os.path.join(company_dir, "ats.md")
    try:
        md = tex2md.convert(company_dir)
    except Exception as e:
        print(f"  [ats] tex2md FAILED for {company}: {type(e).__name__}: {e}")
        return None
    open(ats_md, "w", encoding="utf-8").write(
        "<!-- GENERATED by tex2md.py from sections/*.tex at build time. DO NOT EDIT - "
        "edit the .tex files; this file is overwritten on every build. -->\n\n" + md)
    out = os.path.join(company_dir, "sunil_resume.docx")
    ref = os.path.join(APPLICATIONS_DIR, "ats-reference.docx")
    cmd = ["pandoc", ats_md, "-o", out]
    if os.path.isfile(ref):
        cmd += ["--reference-doc", ref]
    proc = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    if proc.returncode != 0:
        print(proc.stdout.decode(errors="replace"))
        print(f"  [ats] FAILED for {company}")
        return None
    print(f"  [ats] {out}")
    return out


def main():
    ap = argparse.ArgumentParser(description="Build a tailored resume for a company.")
    ap.add_argument("company", help="company folder name under applications/ (e.g. capital-one)")
    ap.add_argument("--pdf-only", action="store_true")
    ap.add_argument("--ats-only", action="store_true")
    args = ap.parse_args()

    company_dir = os.path.join(APPLICATIONS_DIR, args.company)
    if not os.path.isdir(company_dir):
        print(f"No such company folder: {company_dir}")
        print("Create it with: ./jobpilot apply <url>")
        sys.exit(1)

    print(f"Building tailored resume: {args.company}")
    if not args.ats_only:
        build_pdf(company_dir, args.company)
    if not args.pdf_only:
        build_ats(company_dir, args.company)


if __name__ == "__main__":
    main()
